### PR TITLE
Added `includes` method

### LINKED ISSUE #81: Add "includes" method
Add a new `.includes(value|predicate-fn)` method that determines whether the collection includes a certain `value`. The `.includes()` method allows either a dedicated value or a predicate function receiving a collection item (like `.find()`).

Returns `true` if the value is found in the collection or the predicate function returns an item from the collection. Returns false otherwise.

**Notice:** this is basically an alias for the existing `.has` method. 

**Example**

```js
const collection = Collect([ 1, 2, 3 ])

await collection.includes(2)
// true

await collection.includes((value => {
  return value > 5
})
// false
```

### PR DESCRIPTION
**Pull request by lukas-mertens**
I added the includes method as required. It isn't documented in the official documentation yet though.

closes #81

### CODE REVIEW

**Comment by lukas-mertens** [comment]
related to #81

**Comment by marcuspoehls** [comment]
@lukas-mertens Hey Lukas, thank you for the pull request.

Can you please add another test ensuring that the `includes` method also works with plain values and not just callbacks?

**Comment by lukas-mertens** [comment]
Done! I added some additional tests for the `has`-method as well. But as I see it, the types aren't exactly correct, right? Only a `callback: Function` is accepted as a parameter, so if you enforce correct types it wouldn't be possible to pass e.g. a number. Because I didn't want to make the library inconsistent, I just copied it for now, but maybe we should think about how to make that better in the future, what do you think?

**Comment by marcuspoehls** [comment]
@lukas-mertens Hey Lukas, you’re right: the `.has` method allows only a callback function at this point.

It’s a good idea to keep it consistent for now. Let’s tackle the option to check for a specific value in a second iteration. Are you interested in submitting another pull request updating the types and functionality of the `.includes` and `.has` methods to support specific values?

This pull request looks good and I’ll merge it already (and leaving the question for you 😃)

**Pull request merged**
