### PR TITLE
Support sync and async Collections

### PR DESCRIPTION
**Pull request by marcuspoehls**
Up to this point, all collection pipelines are async. That means each pipeline creates a promise which needs to be awaited. This pull request introduces synchronous collections.

### Sync Collections
A collection is synchronous by default. Synchronous collections work like JavaScript’s Array methods. For example, the following pipeline stays a synchronous pipeline:

```js
const Collect = require('@supercharge/collections')

const collection = Collect([1, 2, 3, 4, 5])
  .map(item => item * 2)
  .filter(item => item > 5)
  .sort((a, b) => b -a)

// on sync collections, you must explicitly call `.all()` to retrieve the result

const result = collection.all()
//  [10, 8, 6]
```

### Async Collections
In comparison, a collection becomes async as soon as you provide an async callback method to methods like `map`, `filter`, `find`, and so on:

```js
const Collect = require('@supercharge/collections')

const collection = Collect([1, 2, 3, 4, 5])
  .map(async item => item * 2) // the collection is async from here on
  .filter(item => item > 5)
  .sort((a, b) => b -a)

// async collections must be awaited

const result = await collection
//  [10, 8, 6]
```

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey Vlad, I added support for fully synchronous collections over the last days. I’m happy to hear your opinion on the feature/implementation/and the following questions 😃 

- Do you think it makes sense to support sync and async collections?
- Would you extract sync collections into a separate package?

**My thought process**
At work, I’m in the need of synchronous collections. For me it would be great to have sync support because I can simplify my code from `!!array.find()` to `collection.has()`. I feel like the collection methods are more readable and convenient. That’s why I added support for sync collections. I was also thinking whether it makes sense to just provide a package for the synchronous collections. I’d probably call it towards “Arrays” then and keep “Collections” for async handling

The reason I added sync collections to this package and not a separate one: it’s just a single dependency. Please let me know what you think :)

Thank you!

**Comment by marcuspoehls** [comment]
ntly

**Comment by mcvladthegoat** [comment]
@marcuspoehls Hey Marcus! Sounds great.
For the 1st question: yes :)

And the answer for the 2nd quite bit more complicated:
On the one hand it would be great to have a single package because it easier to maintain (correct me if i'm wrong).
On the other hand, it seems to me that async support should be provided with "smart" wrapper (for ex.: `promisify` for `fs` functionality in nodejs). Honestly, i'm not sure that it is possible at all.

So I think it would be great to have a separate package or "wrapper" (described above) in the future. For now, single package looks good. What do you think?
Thx for your question :)

**Comment by mcvladthegoat** [comment]
@marcuspoehls any updates?

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey, thank you for following up! I appreciate you being sticky :)

You’re right: having sync and async collections in a single package simplifies maintenance. We can quickly add the corresponding sync and async methods.

I like the idea of going with a single package for now. We can split the sync and async handling later when running into issues or maintenance problems. I’ll merge this branch and publish a new release.

@mcvladthegoat Vlad, merging this branch affects your pull request #79. I hope you can resolve the merge issues without much effort!

**Pull request merged**
